stages:
  - build
  - publish
  - deploy

cache:
  paths:
    - node_modules/

build:
  tags:
    - vfast
  stage: build
  image:
    name: node:16.14.0
  script:
    - npm install
    - npm run build
  only:
    - develop
    - main
  artifacts:
    paths:
      - node_modules/

publish:
  tags:
    - vfast
  stage: publish
  before_script:
    - docker version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f || true
    - docker rmi $CI_REGISTRY_IMAGE:latest -f || true
  only:
    - develop
    - main

deploy:
  tags:
    - vfast
  stage: deploy
  only:
    - develop
    - main
  before_script:
    - apk update && apk add openssh-client bash
  script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$K8S_MASTER_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - ssh-keyscan -H -p $K8S_MASTER_PORT $K8S_MASTER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - >
      ssh $K8S_MASTER_USER@$K8S_MASTER_IP -p $K8S_MASTER_PORT
      "bash $K8S_RESTART_SCRIPT_PATH vfast vfast-bo-deployment;
      docker image prune -f;
      docker volume prune -f;"
